# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-19 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('encargado', models.TextField()),
                ('lugar', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('email', models.CharField(max_length=50)),
                ('fecha_nac', models.DateField()),
                ('fecha_ing', models.DateField()),
                ('nota_aud', models.CharField(max_length=2)),
                ('nivel', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ini', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('contenido', models.TextField()),
                ('observaciones', models.TextField()),
                ('nota', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=1)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orquesta.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('email', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=1)),
                ('instrumento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orquesta.Instrumento')),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_sol', models.DateField()),
                ('fecha_ent', models.DateField()),
                ('status', models.CharField(max_length=1)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orquesta.Alumno')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orquesta.Instrumento'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='representante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orquesta.Representante'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='participantes',
            field=models.ManyToManyField(to='orquesta.Alumno'),
        ),
    ]
