# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-20 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orquesta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='apellido',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='representante',
            name='apellido',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
