# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-10 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orquesta', '0006_auto_20181209_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='foto',
            field=models.FileField(default='profile.png', upload_to=''),
        ),
    ]
