# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-10 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orquesta', '0014_auto_20181209_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='foto',
            field=models.ImageField(upload_to='fotos'),
        ),
    ]
