# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-02 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orquesta', '0015_auto_20181209_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='foto',
            field=models.ImageField(default='fotos/profile.png', upload_to='fotos'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='foto',
            field=models.ImageField(default='fotos/profile.png', upload_to='fotos'),
        ),
    ]
