# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-06 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orquesta', '0017_profesor_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha_fin',
            field=models.DateField(default=None),
        ),
    ]
