# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-06 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orquesta', '0020_auto_20190106_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha_ini',
            field=models.DateField(auto_now_add=True),
        ),
    ]
