# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-07 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orquesta', '0021_auto_20190106_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha_fin',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='nota',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
