# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-07 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orquesta', '0022_auto_20190107_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha_fin',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='nota',
            field=models.CharField(blank=True, default=None, max_length=3),
        ),
    ]
