# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-03 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orquesta', '0024_auto_20190107_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='observaciones',
            field=models.TextField(null=True),
        ),
    ]
