# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-03 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orquesta', '0026_auto_20190302_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_ent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
