# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-07 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orquesta', '0027_auto_20190303_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='codigo',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
