# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-12 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orquesta', '0028_solicitud_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='nivel',
            field=models.CharField(choices=[('Concertino', 'Concertino'), ('Principal', 'Principal'), ('Asistente', 'Asistente'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('Practicante', 'Practicante')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='sexo',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1),
        ),
    ]
