# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-14 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orquesta', '0031_auto_20190513_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orquesta.Representante'),
        ),
    ]
