# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-14 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orquesta', '0032_auto_20190513_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='cedula',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='admin',
            name='telefono',
            field=models.BigIntegerField(),
        ),
    ]
