# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-15 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orquesta', '0033_auto_20190514_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representante',
            name='cedula',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='representante',
            name='telefono',
            field=models.BigIntegerField(),
        ),
    ]
