# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-15 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orquesta', '0034_auto_20190514_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='cedula',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='sexo',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='telefono',
            field=models.BigIntegerField(),
        ),
    ]
