# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-15 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orquesta', '0035_auto_20190515_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='tipo',
        ),
    ]
