# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-24 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orquesta', '0037_evaluacion_urlvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='fecha_egr',
            field=models.DateField(blank=True, null=True),
        ),
    ]
