# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-09 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orquesta', '0038_alumno_fecha_egr'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='cod_ins',
            field=models.TextField(blank=True, null=True),
        ),
    ]
