# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-09 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orquesta', '0039_alumno_cod_ins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='cod_ins',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
